### ISSUE TITLE
Structure definition location

### ISSUE THREAD

**Issue by docnux** [nittka/terminology#24]
More a question than a feature request:
I don't know (yet) how xtext works internally, therefore a layman's question:
Where is the default structure of the records defined? Maybe I want to add a data field sometime ...

**Comment by nittka** [comment]
Xtext uses a grammar to define the document structure. You can find the grammar for the Terminology language here https://github.com/nittka/terminology/blob/master/de.itemis.tooling.terminology/src/de/itemis/tooling/terminology/Terminology.xtext

For you the definitions of term (line 65) and entry (line 41) would be most interesting.

It is not possible to extend the grammar at run time. So you cannot simply add your own data fields. There are two basic approaches for "extending" the language:
* Make the additional data field part of the language
* Allow the user to define own datafields within the language

Both have their pros and cons. Note that the text file is only part of the picture. What are the expectations with respect to the search dialog and exporters (in particular the json export for web search)? Depending on those expectations it might be quite a large feature request (additional datafields are not just string key value pairs but key with definable datatype - enum, number, date, string... both as single values or list).

Maybe you can already elaborate on what your use case is. If possible grammar changes should be downward compatible. Otherwise already existing terminologies could not be processed anymore.

**Comment by docnux** [comment]
OK, thanks for the explanation.
I will dig into the xtext documentation sometime as I seems to be very interesting stuff.
Presently I don't need any changes. So: No worries.

**Comment by nittka** [comment]
The human readable explanation of the Terminology language can be found in the wiki 

https://github.com/nittka/terminology/wiki/Terminology-Syntax

If you need an extension of the language, please open a new ticket with a detailed description of the use case, so we can discuss the available options.
